runtime: java
entrypoint: java -jar ./build/libs/shift-manager-server-1.0-SNAPSHOT.jar
env: flex
service: shift-manager-server
runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "17"
handlers:
  - url: /.*
    script: this field is required, but ignored

manual_scaling:
  instances: 1