name: Backend CI-CD Deploy To Prod

on:
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - main

jobs:
  deploy_to_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Gcp auth
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SHIFTMANAGER_409516 }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'

      - name: 'Use gcloud To Deploy Prod'
        run: 'gcloud app deploy --quiet'